name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        - os:
           - linux-latest
           - macos-latest
           - windows-latest
        - nim:
           - version-1-6
           - devel

    name: '${{ matrix.os }} (Nim ${{ matrix.nim }})'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}

      - name: Check build
        run: nimble install -y

      - name: Run tests
        run: nimble test
