name: CI
on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        - os:
           - linux-latest
           - macos-latest
           - windows-latest
        - nim:
           - version-1-6
           - devel

    defaults:
      run:
        shell: ${{ matrix.shell }}

    name: '${{ matrix.os }} (Nim ${{ matrix.nim }})'
    runs-on: ${{ matrix.builder }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}

      - name: Run tests
        shell: bash
        run: |
          nim --version
          nimble --version
          nimble install -y --depsOnly
          nimble test
